# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: postgres
scope: Namespaced
shortDescription: Production-ready PostgreSQL database
longDescription: >
  Using cloud native PG
iconUrl: https://avatars.githubusercontent.com/u/177543
defaultNamespace: postgres
dependencies:
  - name: "cloudnative-pg"
manifests:
  - url: https://pmig.github.io/glasskube-postgres-demo/repo/packages/postgres/v0.0.1+1/cluster.yaml
valueDefinitions:
  replicas:
    type: number
    defaultValue: 2
    metadata:
      description: >
        Number of replicas
    constraints:
      required: true
      minLength: 1
    targets:
      - patch:
          op: add
          path: /spec/instances
        valueTemplate: "{{ . }}"
        resource:
          apiGroup: postgresql.cnpg.io/v1
          kind: Cluster
          name: postgres
          namespace: postgres
  memoryLimit:
    type: text
    defaultValue: "1Gi"
    metadata:
      description: >
        Memory Limit
    targets: []
    constraints:
      required: false
      minLength: 1
  CPULimit:
    type: text
    defaultValue: "2"
    metadata:
      description: >
        CPU Limit Limit
    targets: []
    constraints:
      required: false
      minLength: 1
  autoscale:
    type: boolean
    targets: []
    defaultValue: "false"
